### PR TITLE
View updates - TopBar, Feed View, Events View, ProgressGear

### LINKED ISSUE #11: Twitter Feed - View
Need to make the view prettier.

It's been started. Need to do formatting with images. and who wrote it.

Eventually will need to launch twitter to post when a post is clicked.

### PR DESCRIPTION
**Pull request by Jtfinlay**
Title says it all. Everything is placeholders right now, we'll need to wait for a server to be set up for most of this stuff. If @jviau isn't going to do it I might look into setting up an Azure or nodejs server.

There's a bit of lag when it first loads the image resources in the events view. I'll have to see if there's a way to load them asynchronously? It just makes the sidebar animation kind of choppy when first opened, nothing critical.

In my infinite talent, there's also a 'ProgressGeer' View object, which can be used to replace the basic functionalities of a ProgressBar, except that it's an awesome gear!!! Huzza!

Current colour theme is called 'shit brown'.

Should close #11 for now. #9 still needs server side to update the times.

Thoughts?

### CODE REVIEW

**Comment by jviau** [comment]
Yes I will be doing the NodeJS. I just thought we were waiting for one of us to get MSDN Ultimate for free Azure?

Or I might set it up on my server with Google Cloud Messaging for the push notifications. Will require registering our app with Google console and all that shit. Which is always fun.

**Comment by afontaine** [comment]
NodeJS? Why Node?

(Just curious, also we're not going with Parse?)

Andrew Fontaine

**Comment by Jtfinlay** [comment]
Oh, I hadn't realized we were actually waiting on something. What's the plan on getting it?

**Comment by jviau** [comment]
NodeJS works nicely with twitter streaming.

I will try setting it up on my server first. If not then maybe Azure free trial?

**Comment by Jtfinlay** [comment]
We could always ask @Mobius5150 if he knows how to get one (Mike Blouin).

**Comment by afontaine** [comment]
Ah sounds good to me. Could we Azure free trial into free azure ultimate? I don't see why that wouldn't work...

**Comment by jviau** [comment]
@Jtfinlay - He has MSDN Ultimate so he can get them on his account for sure.
@afontaine - You would think, but they might be very separate things. Who knows. Free trial still requires a credit card though.

I see we are making great use of HipChat /sarcasm

**Comment by afontaine** [comment]
Well I could see having to re-set up everything and migrating over, but the free trial would at least give us somewhere to start.

That's lame. They just want to sneak in and start taking your money once the free trial runs out.

**Comment by Jtfinlay** [comment]
Is the Dreamspark version trial-only?

**Comment by afontaine** [comment]
I thought the Dreamspark version was self-hosted.

**Comment by Jtfinlay** [comment]
Okay, that's the issue. Makes sense

**Comment by jviau** [comment]
Dreamspark is actually just the SDK, which is free anyways.

**Comment by Jtfinlay** [comment]
Well, if we want to start with a free trial we can always migrate over to someone who already has it

**Comment by jviau** [comment]
Okay I will give it a shot. Azure probably still requires registering your app with Google console to get keys and whatnot. The only problem I had with it when I attempted it for Adventure.DateTime was the sha1 keys it needed. Wasn't sure how to make it lineup with the randomly generated debug keys among all our machines.

**Comment by Jtfinlay** [comment]
I have some experience with the delightful key stuff now. We'll figure it out.

**Comment by afontaine** [comment]
Looks good, btw. I like the cards for tweets. Not sure if I prefer the brown or the blue. Any way to force the loading geer? I couldn't seem to make it come up.

**Comment by Jtfinlay** [comment]
Oh yeah, just include it in the xml. I found it's prettiest if you force it to be 75px by 75px.
One sec, i'll type an example

Edit: Just throw this somewhere:
< ca.ippetad.geerweekapp.view.ProgressGeer
    android:layout_width="75px"
    android:layout_height="75px" />

**Comment by Jtfinlay** [comment]
Also, I was thinking I could probably do some masking and have the colour be dynamic, so that we can easily just have some colour templates. That's something to play with later though

**Comment by Jtfinlay** [comment]
Haha, I'm up for that

**Comment by jviau** [comment]
GitHub just spazzed out. Posted my comment several times then deleted them all haha.

**Comment by jviau** [comment]
Anyways, which should I try first: Azure, or set it up on my server?

**Comment by Jtfinlay** [comment]
I'd say Azure

**Comment by afontaine** [comment]
Yeah, Azure is cool.

Geer looks good.

HipChat is surprisingly clunky. Fuck it.

This is good to merge.

**Comment by jviau** [comment]
Alright sounds good.

My Internet is down at work :-(

**Comment by Jtfinlay** [comment]
With travis, and without @edegraff @jesseDtucker helping, @afontaine and I think we should just have a single person's approval be enough. THat sound fine, @jviau ?

**Comment by afontaine** [comment]
@jviau: internet down? How do you live?

**Comment by Jtfinlay** [comment]
@jviau: better yet, how do you post?

**Comment by afontaine** [comment]
@jviau How Can GitHub Be Real If The Internet Isn't Real?

**Comment by jviau** [comment]
Posting from my phone. And with no Internet I  might as well go home for the day.

**Comment by jviau** [comment]
Oh and yes single person is fine. But why aren't those two helping? Are they too good for us? Huh? Is that it? You assets think you're all high and mighty over in Vancouver. Well fuuuuuuuuck you.

**Comment by jviau** [comment]
Heh autocorrect and this app doesn't allow for editing.

**Comment by Mobius5150** [comment]
@Jtfinlay @jviau If you guys wanna dev on the free trial and it runs out we can run it on my Azure for the actual geer week. Don't really have time to set it up right away though.

**Comment by afontaine** [comment]
@Mobius5150 They're both going to MS for they summer, so they'll get their own azure, _right_?

Or are you paying for azure now?

**Comment by Mobius5150** [comment]
@afontaine I _think_ so... My still having MSDN Ultimate may or may not be a bug. I don't ask questions.

Didn't know @jviau was also going. Cool.

**Comment by afontaine** [comment]
Ah okay cool. If not, there's always heroku I suppose, too.

**Comment by edegraff** [comment]
Actually asking for help might help your cause :p

**Comment by Jtfinlay** [comment]
@edegraff: So.... willing to help? Want to do controller stuff for kidnapping? Andrew has started on the View :p

**Comment by edegraff** [comment]
Sure, I can take a look.

**Comment by jviau** [comment]
@Mobius5150 what type of Azure service should I deploy the Node.js twitter streaming on? A VM, Cloudapp, or Website? Or is there a way to just deploy it directly onto my mobile service (I know mobile service can run scheduled jobs, but I guess twitter streaming is an open connection, no a scheduled job?).

And If I am eventually doing a website for administration of events, should I put the website in the same service as the twitter streaming?

**Pull request merged**
